/// <reference path="./Bakefile.d.ts" />

task("clean", { desc: "dist ディレクトリを削除" }, async ({ rm }) => {
  await rm("dist", { recursive: true, force: true });
});

const buildOpts = ["build", "src/cli/main.ts", "--compile"];

// package.json の version を単一の真実の源として src/version.ts へ書き出す。
// suffix は dev ビルドで "-dev" を付け、semver 比較上リリース版より古く扱わせる。
async function writeVersion(suffix: string): Promise<void> {
  const pkg = (await Bun.file("package.json").json()) as { version: string };
  const value = JSON.stringify(`${pkg.version}${suffix}`);
  const banner = "// Auto-generated by Bakefile.ts build task. Do not edit.";
  await Bun.write(
    "src/version.ts",
    `${banner}\nexport const BAKE_VERSION = ${value};\n`,
  );
}

const build = task(
  "build",
  {
    desc: "CLI をビルド",
    deps: ["clean"],
    inputs: ["src/**/*.ts", "test/**/*.test.ts"],
  },
  async ({ cmd }) => {
    await writeVersion("-dev");
    await cmd("bun", [...buildOpts, "--outfile=dist/bake"]);
  },
);

task(
  "build:prod",
  {
    desc: "production 向け CLI ビルド（minify + bytecode で起動高速化・サイズ削減）",
    deps: ["clean"],
    inputs: ["src/**/*.ts"],
  },
  async ({ cmd }) => {
    await writeVersion("");
    await cmd("bun", [
      ...buildOpts,
      "--minify",
      "--bytecode",
      "--sourcemap=none",
      "--outfile=dist/bake",
    ]);
  },
);

const typecheck = task("typecheck", { desc: "型チェック" }, async ({ cmd }) => {
  await cmd("bunx", ["tsc", "--noEmit"]);
});

const fmt = task("fmt", { desc: "フォーマットチェック" }, async ({ cmd }) => {
  await cmd("bunx", ["biome", "check", "."]);
});

const test = task("test", { desc: "テストを実行" }, async ({ cmd }) => {
  await cmd("bun", ["test"]);
});

task.each(
  "sanity",
  {
    desc: "型チェック・フォーマット・ビルド・テストをまとめて実行",
    done: "✨ All checks passed! You're good to go.",
  },
  typecheck,
  fmt,
  build,
  test,
);

// scripts/dev-server.ts は起動時に "Server running at ..." を出力するので、
// その行を ready の目印にする（ready 未指定だと起動直後に ready 扱いになってしまい、
// 実際に listen できたかを確認できない）。
const server1 = task.service(
  "server1",
  { ready: { log: "Server running at" } },
  async ({ cmd }) => {
    await cmd("bun", ["run", "--hot", "scripts/dev-server.ts"], {
      env: { PORT: "3000" },
    });
  },
);

const server2 = task.service(
  "server2",
  { ready: { log: "Server running at" } },
  async ({ cmd }) => {
    await cmd("bun", ["run", "--hot", "./dev-server.ts"], {
      env: { PORT: "3001" },
      cwd: "scripts/",
    });
  },
);

// server1 / server2 は互いに依存しない独立したサーバなので、1 つのグループにまとめて同時起動する
// （配列で束ねなかった場合は「起動順」として順に起動されてしまう）。
task.compose("dev", { desc: "run servers" }, [server1, server2]);

task.default(build);
